modal/urls.py
from django.conf.urls import url
from django.contrib import admin
from car import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list$', views.ListView.as_view(), name='list'),
    url(r'^detail/(?P<pk>\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^form$', views.FormView.as_view(), name='form'),
    url(r'^create$', views.CreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)$', views.UpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)$', views.DeleteView.as_view(), name='delete'),
]

car/models.py
from django.db import models
from django.urls import reverse
from django import forms

# Create your models here.
class Car(models.Model):
    name = models.CharField(max_length=30)
    sn = models.CharField(max_length=30)
    last_accessed = models.DateTimeField(null=True)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

car/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator

CAR_NUMBER_REGEX = RegexValidator(regex=r'^\d{2}-\d{4}$', message='ต้องเป็นเลขทะเบียน รูปแบบ 10-1234')

class CarForm(ModelForm):
    message = forms.CharField(label='ข้อความ', widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        print(self.cleaned_data['message'])

    class Meta:
        model = Car
        fields = ['name', 'sn']
        labels = {
            'name': _('ชื่อ'),
            'sn': _('รหัส'),
        }
        widgets = {
            'sn': forms.TextInput(attrs={'placeholder':'10-1234'}),
        }
        help_texts = {
            'name': _('อะไรก็ได้ เท่ๆ'),
        }
        error_messages = {
            'name': {
                'max_length': _("This writer's name is too long."),
            },
        }

class CarUpdateForm(ModelForm):
    sn = forms.CharField(label='รหัส (regex)',
        validators=[CAR_NUMBER_REGEX])

    class Meta:
        model = Car
        fields = ['name', 'sn']
        labels = {
            'name': _('ชื่อ'),
        }
        error_messages = {
            'name': {
                'max_length': _("This writer's name is too long."),
            },
        }

# https://docs.djangoproject.com/en/1.11/topics/forms/modelforms/

car/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin
from .models import Car
from .forms import CarForm, CarUpdateForm
from django.utils import timezone
from django.urls import reverse_lazy

# https://docs.djangoproject.com/en/1.11/ref/class-based-views/generic-display/
class IndexView(TemplateView):
    template_name = 'car/index.html'

class ListView(ListView):
    template_name = 'car/car_list.html' # default : '_list.html'
    context_object_name = 'car_list' # default : 'object_list'
    queryset = Car.objects.all()

# url : pk
class DetailView(DetailView):
    template_name = 'car/car_detail.html' # default : '_detail.html'
    context_object_name = 'car' # default : 'object'
    queryset = Car.objects.all()

    def get_object(self):
        # Call the superclass
        object = super(DetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Return the object
        return object

# https://docs.djangoproject.com/en/1.11/ref/class-based-views/generic-editing/
class FormView(FormView):
    template_name = 'car/form.html'
    success_url = '/'
    form_class = CarForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(FormView, self).form_valid(form)

class CreateView(CreateView):
    model = Car
    template_name_suffix = '_create_form' # default : '_form.html'
    success_url = '/create' # or model - def get_absolute_url(self):
    fields = ['name', 'sn']

    def get_context_data(self):
        context = super(CreateView, self).get_context_data()
        context['car_list'] = Car.objects.all()
        return context

    #def form_valid(self, form):
    #    print('asdasdasdasd')
    #    return super(CreateView, self).form_valid(form)

# url : pk
class UpdateView(UpdateView):
    model = Car
    template_name_suffix = '_update_form' # default : '_form.html'
    # success_url = '/list' # or model - def get_absolute_url(self):
    form_class = CarUpdateForm #fields = ['name', 'sn']

# url : pk
class DeleteView(DeleteView):
    model = Car
    template_name_suffix = '_check_delete' # default : '_confirm_delete.html'
    success_url = reverse_lazy('list')

# https://docs.djangoproject.com/en/1.11/ref/class-based-views/mixins/

# https://docs.djangoproject.com/en/1.11/topics/forms/modelforms/

car/templates/car/car_check_delete.html
<form action="" method="POST">
  {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }} - {{ object.sn }}"?</p>
    <input type="submit" value="Confirm" />
</form>

car/templates/car/car_create_form.html
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
<br><br>

<table border="1">
  <tr bgcolor="#adcdef">
    <td>name</td>
    <td>sn</td>
    <td>last_accessed</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  {% for car in car_list %}
  <tr>
    <td>{{ car.name }}</td>
    <td>{{ car.sn }}</td>
    <td>{{ car.last_accessed.time }}</td>
    <td><a href="detail/{{ car.pk }}">DETAIL</a></td>
    <td><a data-toggle="modal" data-target="#myModal" href="update/{{ car.pk }}">MODAL</a></td>
    <td><a href="update/{{ car.pk }}">UPDATE</a></td>
    <td><a href="delete/{{ car.pk }}">DELETE</a></td>
  </tr>
  {% endfor %}
</table>

<a href="/">INDEX</a>

car/templates/car/car_detail.html
Car Detail
<hr>
{{ car.name }} - {{ car.sn }} - {{ car.last_accessed }}
<br><br>
<a href="/list">LIST</a>

car/templates/car/car_list.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
  td{
    width: 150px;
  }
</style>
<!-- Modal -->
<div id="myModal" class="modal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content"></div>
  </div>
</div>
<!-- end Modal -->

Car List
<hr>
<table border="1">
  <tr bgcolor="#adcdef">
    <td>name</td>
    <td>sn</td>
    <td>last_accessed</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  {% for car in car_list %}
  <tr>
    <td>{{ car.name }}</td>
    <td>{{ car.sn }}</td>
    <td>{{ car.last_accessed.time }}</td>
    <td><a href="detail/{{ car.pk }}">DETAIL</a></td>
    <td><a data-toggle="modal" data-target="#myModal" href="update/{{ car.pk }}">MODAL</a></td>
    <td><a href="update/{{ car.pk }}">UPDATE</a></td>
    <td><a href="delete/{{ car.pk }}">DELETE</a></td>
  </tr>
  {% endfor %}
</table>
<br><br>
<a href="/">INDEX</a>

car/templates/car/car_update_form.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<form action="{% url 'update' object.pk %}" method="POST">
  <div class="modal-header">
    <h4 class="modal-title">แก้ไขข้อมูล</h4>
  </div>
  <div class="modal-body">
    <div id="error"></div>
    {% csrf_token %}
    {{ form.as_p }}
  </div>
  <div class="modal-footer">
    <!--input type="submit" value="Update" /-->
    <input type="button" id="id_button" value="Update" />
  </div>
</form>
<br><br>
<a href="/">INDEX</a>

<script>
  $("#modal").on('hidden.bs.modal', function(){
    $(this).data('bs.modal', null);
  });

  $("#id_button").click(function(){
    regex = /^\d{2}-\d{4}$/g;
    str = $("#id_sn").val();
    if(regex.exec(str)){
      $("form").submit();
    }
    else{
      $("#error").html("ใส่ผิดนะจ๊ะ");
    }
  });
</script>

car/templates/car/form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message" />
</form>
<br><br>
<a href="/">INDEX</a>

car/templates/car/index.html
Hello World!
<hr>
<a href="list">LIST</a>
<br><br>
<a href="form">FORM</a>
<br><br>
<a href="create">CREATE FORM</a>
<br><br>